/* 하브루타 스터디 페어매칭용 상수 */

export const crewObj = {
  곤이: {
    isActive: false,
    studyTrioCount: 1,
    prevMissionPairs: ['체프', '카일', '썬', '유조', '심바', '디토', '엘라', '크리스'],
    prevStudyPairs: ['그루밍', '도비', '디토 피터', '브랜', '지그', '체프', '하루', '유조', '서니', '크리스'],
    img: 'https://avatars.githubusercontent.com/u/59409762?v=4',
  },
  도비: {
    isActive: true,
    studyTrioCount: 1,
    prevMissionPairs: ['주모', '콜린', '서니', '카일', '브콜', '체프', '엘라'],
    prevStudyPairs: ['디토', '곤이', '그루밍', '체프', '크리스', '썬', '카일', '유조', '피터'],
    img: 'https://avatars.githubusercontent.com/u/42544600?v=4',
  },
  디토: {
    isActive: true,
    studyTrioCount: 1,
    prevMissionPairs: ['인치', '크리스', '하루', '신세한탄', '썬', '곤이', '엘라', '주모'],
    prevStudyPairs: ['도비', '곤이', '피터', '유조', '체프', '지그', '콜린', '하루', '썬'],
    img: 'https://avatars.githubusercontent.com/u/64782636?v=4',
  },
  브랜: {
    isActive: false,
    studyTrioCount: 1,
    prevMissionPairs: ['카일', '동동', '유조', '그루밍', '심바', '지그', '서니', '브콜'],
    prevStudyPairs: ['미키', '인치', '썬', '곤이', '피터', '하루', '그루밍', '체프', '콜린', '유조'],
    img: 'https://avatars.githubusercontent.com/u/52202474?v=4',
  },
  서니: {
    isActive: true,
    studyTrioCount: 0,
    prevMissionPairs: ['티케', '체프', '도비', '지그', '신세한탄', '브랜', '콜린'],
    prevStudyPairs: ['크리스', '곤이'],
    img: 'https://avatars.githubusercontent.com/u/67677561?v=4',
  },
  썬: {
    isActive: false,
    studyTrioCount: 1,
    prevMissionPairs: ['콜린', '하루', '곤이', '브콜', '디토', '파노', '피터'],
    prevStudyPairs: ['유조', '미키', '브랜', '피터', '그루밍', '카일', '도비', '크리스', '지그', '디토', '하루'],
    img: 'https://avatars.githubusercontent.com/u/45230497?v=4',
  },
  유조: {
    isActive: true,
    studyTrioCount: 1,
    prevMissionPairs: ['하루', '심바', '브랜', '곤이', '동동', '티케', '체프', '지그'],
    prevStudyPairs: ['썬', '지그', '미키', '디토', '콜린', '하루', '도비', '곤이', '브랜', '브랜'],
    img: 'https://avatars.githubusercontent.com/u/61097373?v=4',
  },
  지그: {
    isActive: false,
    studyTrioCount: 1,
    prevMissionPairs: ['피터', '티케', '심바', '서니', '브랜', '콜린', '체프', '유조'],
    prevStudyPairs: ['인치', '체프', '유조', '콜린', '카일', '곤이', '디토', '썬', '하루', '피터'],
    img: 'https://avatars.githubusercontent.com/u/44080404?v=4',
  },
  크리스: {
    isActive: true,
    studyTrioCount: 0,
    prevMissionPairs: ['브콜', '디토', '미키', '피터', '인치', '파노', '주모', '곤이'],
    prevStudyPairs: ['파노', '카일', '체프', '하루', '도비', '그루밍', '썬', '서니', '크리스', '곤이'],
    img: 'https://avatars.githubusercontent.com/u/32982670?v=4',
  },
  피터: {
    isActive: true,
    studyTrioCount: 2,
    prevMissionPairs: ['지그', '미키', '체프', '크리스', '그루밍', '심바', '썬'],
    prevStudyPairs: ['하루', '파노', '디토', '곤이', '썬', '브랜', '콜린', '카일', '도비', '크리스', '지그'],
    img: 'https://avatars.githubusercontent.com/u/42052110?v=4',
  },
  하루: {
    isActive: true,
    studyTrioCount: false,
    prevMissionPairs: ['유조', '썬', '디토', '동동', '주모', '신세한탄', '심바'],
    prevStudyPairs: ['피터', '그루밍', '파노', '크리스', '유조, 콜린', '브랜', '곤이', '디토', '지그', '썬'],
    img: 'https://avatars.githubusercontent.com/u/60066472?v=4',
  },
};
